TRAC-1112: Refactored bild pageName functionality
spring-media/ds_cmp_tealium_extension pull request #15
Opened 2021-11-23 11:44 UTC by mehakraza

2021-11-24 11:13 UTC, HeikoKampe requested changes

2021-11-24 11:13 UTC, HeikoKampe commented on tests/doPlugins_global.test.js
> +    });
These two test are implicitly testing a functionality which is already tested (isHome).
A different approach would be to mock isHome() for the test and let the mocked function return true.
The advantage would be the de-coupling of the unit under test from its dependency. As a result, we would only need one test for the above scenario. And if the implementation of the dependency would change in the future (eg. different page_id) we would not need to update this test as a consequence.

2021-11-24 11:13 UTC, HeikoKampe commented on tests/doPlugins_global.test.js
> +describe('Bild pagename functionalities', () => {
I think it would be helpful to have the exact unit name (bildPageName) as part of the description title.
Makes it easier to understand which unit exactly gets tested here.

2021-11-24 15:42 UTC, nilbob commented
@mehakraza: Thx a lot. it looks good to me.

2021-11-24 15:42 UTC, nilbob approved these changes
Looks good to me :)

2021-11-25 13:11 UTC, HeikoKampe approved these changes
Well done!

2021-11-26 12:18 UTC, merged