TRAC-1159: Scroll depth refactored
spring-media/ds_cmp_tealium_extension pull request #30
Opened 2021-12-16 13:44 UTC by mehakraza

2021-12-21 07:41 UTC, HeikoKampe requested changes

2021-12-21 07:41 UTC, HeikoKampe commented on extensions/doPlugins_global.js
> +        return !!s.pageName && s.pageName !== '';
Additional check for empty string is not necessary. !!s.pageName covers empty strings.

2021-12-21 07:41 UTC, HeikoKampe commented on extensions/doPlugins_global.js
> +    },
The way functions and conditions are nested makes it a bit hard to read and understand. Here is an idea of a simpler structuring:

```
setScrollDepthData: function (s) {
        if (s.pageName) {
            const prevPage = this.setPreviousPage(s);
            if (prevPage) {
                s.getPercentPageViewed(prevPage);
                this.setData(s);
            }
        }
    }
```

2021-12-21 07:41 UTC, HeikoKampe commented on extensions/doPlugins_global.js
> +        if (this.isPrevPageDefined(s)) {
I am big fan of wrapping complicated operators of an condition in a utility function. But if it is a simple truthy/falsy check it adds no value.

2021-12-21 07:41 UTC, HeikoKampe commented on extensions/doPlugins_global.js
> +    s._scrollDepthObj.setScrollDepthData(s);
The function s.getPercentPageViewed() uses a custom cookies for storing the scroll-depth data. This is only allowed after user has given consent. Therefore a consent check might be needed here. We should discuss this with the team.

2021-12-21 09:04 UTC, HeikoKampe commented on tests/doplugins/doplugins_scroll_depth.test.js
> +            };
Making a copy of the sObject can be moved to the beforeEach hook

2021-12-21 10:47 UTC, mehakraza commented on extensions/doPlugins_global.js
> +        return !!s.pageName && s.pageName !== '';
Thanks for pointing out. Updated.

2021-12-21 11:08 UTC, mehakraza commented on extensions/doPlugins_global.js
> +        if (this.isPrevPageDefined(s)) {
I agree. Moved the check in if condition.

2021-12-21 13:31 UTC, mehakraza commented on extensions/doPlugins_global.js
> +    s._scrollDepthObj.setScrollDepthData(s);
The consent check was present inside the scroll depth old implementation in some places and it was decided that it is not necessary there.

2021-12-21 13:48 UTC, mehakraza commented on extensions/doPlugins_global.js
> +    },
This data is only set once here in the scroll depth context so a separate function would not serve the purpose of reusability but if this implementation decreases readability then there's no harm in moving it to a separate function. Updated in the last commit.

2021-12-21 13:58 UTC, HeikoKampe commented on extensions/doPlugins_global.js
> +    s._scrollDepthObj.setScrollDepthData(s);
:+1:

2021-12-22 11:13 UTC, mehakraza commented on tests/doplugins/doplugins_scroll_depth.test.js
> +            };
Updated.

2021-12-22 14:59 UTC, HeikoKampe approved these changes
Only a view minor issues.

2021-12-22 14:59 UTC, HeikoKampe commented on tests/doplugins/doplugins_scroll_depth.test.js
> +        it('should set the right _prevPage if docType is article or video and page is not premium', () => {
As we discussed ... Functionality is implemented and tested in other unit.

2021-12-22 14:59 UTC, HeikoKampe commented on tests/doplugins/doplugins_scroll_depth.test.js
> +            jest.spyOn(s, 'getPercentPageViewed').mockImplementation(jest.fn());
MockImplementation creates internally an empty function. Passing in jest.fn() is therefore not needed. 

jest.spyOn(s, 'getPercentPageViewed').mockImplementation(jest.fn());

2021-12-22 14:59 UTC, HeikoKampe commented on extensions/doPlugins_global.js
> +        s.events = s.apl(s.events, event46, ',', 1);
Here we should use our new way of setting the events property:
s._eventsObj.addEvent(event45);

2021-12-24 10:34 UTC, mehakraza commented on extensions/doPlugins_global.js
> +        return !!doc_type && (doc_type === 'article' || doc_type === 'video');
Updated

2021-12-24 10:35 UTC, merged