Refactored teaser tracking eVars implementation
spring-media/ds_cmp_tealium_extension pull request #34
Opened 2022-01-05 09:36 UTC by mehakraza

2022-01-17 09:13 UTC, HeikoKampe requested changes

2022-01-17 09:13 UTC, HeikoKampe commented on extensions/doPlugins_global.js
> +        && s._ppvPreviousPage.indexOf('home') === 0) {
Putting the condition into a utility function might improve readability and testability.

2022-01-17 09:13 UTC, HeikoKampe commented on tests/doplugins/doplugins_teaser_tracking_evars.test.js
> +        sessionStorage.removeItem('home_teaser_info');
Mocking away the sessionStorage would avoid the risk of leaving states behind. Could be done like the existing (but not used anymore) implementation of the localStorage mock (see mocks/browserMocks.js)

2022-01-17 13:33 UTC, mehakraza commented on extensions/doPlugins_global.js
> +                    || window.utag.data.page_type;
getDocType() does not contain the page types used here. I have created a separate utility function for these page types.

2022-01-17 13:37 UTC, mehakraza commented on extensions/doPlugins_global.js
> +        && s._ppvPreviousPage.indexOf('home') === 0) {
This condition is only used in a single place inside the _setTeaserTrackingEvars function. Converting the implementation to an object just to add a testable utility function to accomodate this condition without the need of reusability is not worth the effort IMO.

2022-01-17 13:42 UTC, mehakraza commented on tests/doplugins/doplugins_teaser_tracking_evars.test.js
> +        sessionStorage.removeItem('home_teaser_info');
Session storage is used only in teaser tracking eVar setup with the addition of a single key which is removed after each test so there is no risk of uncleared state. If we need to use session storage in more places we can consider having a mock.

2022-01-17 14:40 UTC, HeikoKampe commented on extensions/doPlugins_global.js
> +    },
Why not add page_document_type and page_mapped_doctype_for_pagename to the existing function? Then it would be clear that it is the same functionality and needs some normalization on Tealium profile level. And this new function is only used by the teaser tracking.

2022-01-17 14:47 UTC, HeikoKampe commented on extensions/doPlugins_global.js
> +        && s._ppvPreviousPage.indexOf('home') === 0) {
ok

2022-01-17 14:47 UTC, HeikoKampe commented on tests/doplugins/doplugins_teaser_tracking_evars.test.js
> +        sessionStorage.removeItem('home_teaser_info');
ok

2022-01-19 10:38 UTC, HeikoKampe approved these changes

2022-01-19 11:09 UTC, merged