TRAC_1222 Adobe CW extension refactoring
spring-media/ds_cmp_tealium_extension pull request #65
Opened 2022-03-24 11:42 UTC by akaxsp22

https://as-jira.axelspringer.de/browse/TRAC-1222

2022-03-24 14:30 UTC, HeikoKampe commented on extensions/my_CW.js
> +
A comment with an example string would be nice here.

2022-04-06 07:13 UTC, akaxsp22 commented on extensions/my_CW.js
> +        const dow = date.getDate() - date.getDay() + 1;
In case when talking about weeks that start in December of 'previous year,' and end in January of 'current year', the year should be the 'previous year'. So I am fetching the year of the first day of the week

2022-04-08 12:50 UTC, HeikoKampe commented on extensions/my_CW.js
> +        return new Date(newDate.setDate(dow));
No need to create two new date objects here. Here is an alternative approach:

const dow = date.getDate() - date.getDay() + day;
const dowDate = new Date(date.getTime());
dowDate.setDate(dow);
return dowDate;

2022-04-08 12:54 UTC, HeikoKampe commented on extensions/my_CW.js
> +    getCW: function() {
A comment with an example string of what would be returned by getCW() what also be useful

2022-04-12 07:00 UTC, HeikoKampe requested changes
My last comments, I promise ;-)

2022-04-12 07:00 UTC, HeikoKampe commented on tests/my_CW.test.js
> +        cw = {...myCW};
Because your tests are not changing the imported myCW object, creating a fresh copy of the object for each test is not necessary.

2022-04-12 07:00 UTC, HeikoKampe commented on tests/my_CW.test.js
> +            expect(leadingZeroMock).toHaveBeenCalledWith(1);
This would not fail if unit calls leadingZeroMock(1) only once. You need to do it like this:

expect(leadingZeroMock).toHaveBeenNthCalledWith(0, 1);
expect(leadingZeroMock).toHaveBeenNthCalledWith(1, 1);

2022-04-12 07:00 UTC, HeikoKampe commented on tests/my_CW.test.js
> +            dateMock.mockReturnValue(mockDate);
You are implicitly creating global variables here by omitting the variable type declaration (var, let or const).
If you do not need to modify the spy after creation you can also call the spy method without assigning the returned object to any variable:

jest.spyOn(global, 'Date').mockImplementation().dateMock.mockReturnValue(mockDate);

2022-04-12 07:00 UTC, HeikoKampe commented on tests/my_CW.test.js
> +            toStringMock = jest.spyOn(global, 'toString');
These spies do nothing! Either use them, mock implementations and check correct calls or remove them.

2022-04-12 07:00 UTC, HeikoKampe commented on extensions/my_CW.js
> +s._myCW = _myCW;
Just realized that the current usage of this module looks like this:
window.utag.data.myCW

We should take care that we do not break this legacy usage by also exposing getCW to this property of the data layer. Eg.

window.utag.data.myCW = _myCW.getCW;

2022-04-28 08:38 UTC, merged