TRAC-1336 added condition to setViewType
spring-media/ds_cmp_tealium_extension pull request #78
Opened 2022-04-28 09:23 UTC by akaxsp22

https://as-jira.axelspringer.de/browse/TRAC-1336

articleViewType events should not be set when there is an ad wall. Added this condition in function setViewType (line 275)

2022-04-28 10:51 UTC, HeikoKampe requested changes

2022-04-28 10:51 UTC, HeikoKampe commented on extensions/doPlugins_global.js
> +        if (s._utils.isArticlePage() && window.utag.data.adobe_doc_type != 'ad wall') {
Please add unit tests for this condition.

2022-05-02 09:44 UTC, HeikoKampe approved these changes
:+1:

2022-05-02 12:22 UTC, akaxsp22 commented
Added change to global doPlugins extension function setViewTypes and new unit test to check condition

2022-05-02 12:23 UTC, merged